name: Master PR

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.x
    - name: Install dependencies
      run: dotnet restore
    - name: Install CodeCov.Tool
      run: dotnet tool install -g Codecov.Tool
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal --collect:"XPlat Code Coverage"
    - name: Report Coverage
      uses: codecov/codecov-action@v1
      with:
        file: ./SharpSanity.Tests/TestResults/**/coverage.cobertura.xml
